### ISSUE TITLE
KeyError: 'items'

### ISSUE THREAD

**Issue by s1nnohlakes** [omerbselvi/pewdiepie-vs-tseries#1]
Running the main.py script retuns 'KeyError: 'items'

**Comment by omerbselvi** [comment]
Have you obtained your API key from console.developers.google.com ? If so, you need to enable "YouTube Data API" for your key. Then run the script again.

<img width="1674" alt="yt_api" src="https://user-images.githubusercontent.com/15899104/70372853-52987a00-18f5-11ea-8768-cd28d5507703.png">

And the other thing is, Youtube Data API abbreviates the number of subscribers that the channel have, you can find more information here: https://support.google.com/youtube/thread/6543166?hl=en
So the output of the program is like this now:

<img width="795" alt="api" src="https://user-images.githubusercontent.com/15899104/70372988-1c5bfa00-18f7-11ea-9909-83cf38ec6e51.png">

By the time i made this project subscriber counts were not abbreviated.

**Comment by s1nnohlakes** [comment]
Can I change the channel instead of PewDiePie and T-Series?
And also, yes I obtained my API key

**Comment by omerbselvi** [comment]
Yeah sure you can change the channel, just change the usernames in animate() method:
![image](https://user-images.githubusercontent.com/15899104/70373144-f97e1580-18f7-11ea-98fd-5f544a9518e2.png)

**Comment by s1nnohlakes** [comment]
Ok thanks, and also can it be channel ID?

**Comment by omerbselvi** [comment]
It can be, but for that you need to change the "url" variable like this
`url = "https://www.googleapis.com/youtube/v3/channels?part=statistics&id={}&key={}"`
and it should work.

**Comment by s1nnohlakes** [comment]
Ok thanks
